export const ErrorCodes = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PROJECT_REVISION_CONFLICT: "PROJECT_REVISION_CONFLICT",
  STEP_INVALID_TRANSITION: "STEP_INVALID_TRANSITION",
  PAYMENT_NOT_ALLOWED: "PAYMENT_NOT_ALLOWED",
  ENTITLEMENT_REQUIRED: "ENTITLEMENT_REQUIRED",
  AGENT_NOT_RETRYABLE: "AGENT_NOT_RETRYABLE",
  QUALITY_WARNING: "QUALITY_WARNING",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
